services:
  angular:
    build:
      context: ../infinite_quiz
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    depends_on:
      - symfony
    volumes:
      - ../infinite_quiz:/var/www/html/infinite_quiz
      - /var/www/html/infinite_quiz/node_modules

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html/infinite_quiz_api
    entrypoint: /usr/local/bin/docker-entrypoint.sh

  mysql:
    image: mysql:latest 
    command: --innodb-buffer-pool-size=512M
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
