services:
  angular:
    build:
      context: ../infinite_quiz
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    depends_on:
      - symfony
    volumes:
      - ../infinite_quiz:/var/www/html/infinite_quiz
      # pour éviter les conflits lié au node_modules :
      - /var/www/html/infinite_quiz/node_modules
      
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    environment:
      DATABASE_URL: mysql://infinite:infinite@mysql:3306/infinite_quiz_api?serverVersion=8&charset=utf8mb4
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html/infinite_quiz_api
    entrypoint: /usr/local/bin/docker-entrypoint.sh

  mysql:
    image: mysql:latest 
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infinite_quiz_api
      MYSQL_USER: infinite
      MYSQL_PASSWORD: infinite
    command: --innodb-buffer-pool-size=512M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:

