name: PHP Composer

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.6'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate SSL Keys
      run: |
        mkdir -p certs
        # Générer la clé privée
        openssl genpkey -algorithm RSA -out certs/test_private.key -pkeyopt rsa_keygen_bits:2048
        # Générer la clé publique
        openssl rsa -pubout -in certs/test_private.key -out certs/test_public.key
        # Générer un certificat auto-signé
        openssl req -new -x509 -key certs/test_private.key -out certs/test_cert.crt -days 365 -subj "/CN=localhost"
      shell: bash

    - name: Run PHP test suite
      run: composer run-script test

    - name: Run Newman Tests
      run: |
        npm install -g newman
        newman run postman/postman_collection.json -e postman/postman_environment.json \
          --global-var "ssl_cert=$(cat certs/test_cert.crt)" \
          --global-var "ssl_key=$(cat certs/test_private.key)"
      shell: bash

    - name: Clean up generated keys
      if: always()
      run: rm -rf certs/
