name: PHP Composer

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.6'
        extensions: pdo_mysql

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Wait for MySQL to be ready
      run: sleep 15

    - name: Set up database
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:update --force --env=test
      env:
        DATABASE_URL: "mysql://root:root@127.0.0.1:3306/test_db"

    - name: Generate SSL Keys
      run: |
        mkdir -p certs
        openssl genpkey -algorithm RSA -out certs/test_private.key -pkeyopt rsa_keygen_bits:2048
        openssl rsa -pubout -in certs/test_private.key -out certs/test_public.key
        openssl req -new -x509 -key certs/test_private.key -out certs/test_cert.crt -days 365 -subj "/CN=localhost"
      shell: bash

    - name: Start PHP server
      run: |
        php -S 127.0.0.1:8000 -t public &
        sleep 5
      shell: bash

    - name: Run PHP test suite
      run: composer run-script test

    - name: Run Newman Tests
      run: |
        npm install -g newman
        newman run postman/postman_collection.json -e postman/postman_environment.json \
          --global-var "ssl_cert=$(cat certs/test_cert.crt)" \
          --global-var "ssl_key=$(cat certs/test_private.key)"
      shell: bash

    - name: Clean up generated keys
      if: always()
      run: rm -rf certs/
